name: Sync taxonomy to Notion
on:
  push:
    branches: [ "main" ]
    paths:
      - "schema/**"
      - "mapping/**"
      - "scripts/**"
      - "requirements.txt"
  workflow_dispatch: {}

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
      - run: python scripts/validate.py
      - env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
        run: python scripts/sync_notion.py
